#!/usr/bin/env bash
# Enable the existing OpenBolt stack on a dedicated GUI console.
# GUI already runs: sudo -E -u bolt bolt -i /etc/puppetlabs/bolt/inventory.yaml
#                   --project /etc/puppetlabs/bolt
#
# Idempotent. Run as root on each console (openvox.pdxc / openvox.atlc).
# Product names: OpenBolt / OpenVoxDB. Paths stay puppet.
set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi

BOLT_DIR=/etc/puppetlabs/bolt
GUI_ENV=/opt/openvox-gui/config/.env
PLUGIN_SRC=/opt/openvox-gui/bolt-plugin/openvox_enc
BOLT_BIN=""
for c in /opt/puppetlabs/bolt/bin/bolt /opt/puppetlabs/bin/bolt; do
  [[ -x $c ]] && BOLT_BIN=$c && break
done

read_env() {
  local key=$1
  [[ -f $GUI_ENV ]] || return 0
  grep -E "^${key}=" "$GUI_ENV" | tail -1 | cut -d= -f2- | tr -d '"' | tr -d "'"
}

if [[ -z $BOLT_BIN ]]; then
  echo "OpenBolt binary not found. Install: yum install -y openbolt" >&2
  exit 1
fi
echo "OpenBolt: $($BOLT_BIN --version 2>/dev/null || echo unknown) ($BOLT_BIN)"

if ! id bolt &>/dev/null; then
  useradd -r -m -s /bin/bash bolt
  echo "Created user bolt"
fi

install -d -o root -g bolt -m 0750 "$BOLT_DIR"
install -d -o root -g bolt -m 0750 "$BOLT_DIR/modules"
install -d -o root -g bolt -m 0750 "$BOLT_DIR/ssl"

if [[ ! -f $BOLT_DIR/bolt-project.yaml ]]; then
  cat > "$BOLT_DIR/bolt-project.yaml" << 'EOF'
---
name: openvox-gui
modulepath:
  - /etc/puppetlabs/bolt/modules
EOF
  chown root:bolt "$BOLT_DIR/bolt-project.yaml"
  chmod 640 "$BOLT_DIR/bolt-project.yaml"
  echo "Wrote $BOLT_DIR/bolt-project.yaml"
fi

if [[ -d $PLUGIN_SRC ]]; then
  rm -rf "$BOLT_DIR/modules/openvox_enc"
  cp -a "$PLUGIN_SRC" "$BOLT_DIR/modules/openvox_enc"
  chown -R root:bolt "$BOLT_DIR/modules/openvox_enc"
  echo "Installed openvox_enc plugin"
else
  echo "WARN: $PLUGIN_SRC missing — ENC plugin skipped" >&2
fi

if [[ ! -f $BOLT_DIR/id_bolt ]]; then
  ssh-keygen -t ed25519 -N "" -f "$BOLT_DIR/id_bolt" -C "openvox-gui-bolt@$(hostname -f)" >/dev/null
  chown root:bolt "$BOLT_DIR/id_bolt" "$BOLT_DIR/id_bolt.pub"
  chmod 640 "$BOLT_DIR/id_bolt"
  chmod 644 "$BOLT_DIR/id_bolt.pub"
  echo "Generated $BOLT_DIR/id_bolt"
fi
echo "Bolt pubkey (install as bolt@ on every estate host):"
cat "$BOLT_DIR/id_bolt.pub"

PDB_HOST=$(read_env OPENVOX_GUI_PUPPETDB_HOST)
PDB_PORT=$(read_env OPENVOX_GUI_PUPPETDB_PORT)
CERT=$(read_env OPENVOX_GUI_PUPPET_SSL_CERT)
KEY=$(read_env OPENVOX_GUI_PUPPET_SSL_KEY)
CA=$(read_env OPENVOX_GUI_PUPPET_SSL_CA)
PDB_HOST=${PDB_HOST:-ovdb.corp.int-x.ai}
PDB_PORT=${PDB_PORT:-8081}
CERT=${CERT:-/etc/puppetlabs/puppet/ssl/certs/$(hostname -f).pem}
KEY=${KEY:-/etc/puppetlabs/puppet/ssl/private_keys/$(hostname -f).pem}
CA=${CA:-/etc/puppetlabs/puppet/ssl/certs/ca.pem}

if [[ ! -f $CERT || ! -f $KEY || ! -f $CA ]]; then
  echo "WARN: agent PEMs missing (cert=$CERT). Inventory will still be written." >&2
else
  # bolt must read the private key (640 puppet:puppet by default)
  if command -v setfacl &>/dev/null; then
    setfacl -m u:bolt:r "$KEY" "$CERT" "$CA" 2>/dev/null || true
  fi
  install -o root -g bolt -m 644 "$CA" "$BOLT_DIR/ssl/ca.pem"
  install -o root -g bolt -m 644 "$CERT" "$BOLT_DIR/ssl/cert.pem"
  install -o root -g bolt -m 640 "$KEY" "$BOLT_DIR/ssl/key.pem"
  CA=$BOLT_DIR/ssl/ca.pem
  CERT=$BOLT_DIR/ssl/cert.pem
  KEY=$BOLT_DIR/ssl/key.pem
  echo "Copied agent PEMs to $BOLT_DIR/ssl for the bolt user"
fi

if [[ ! -f $BOLT_DIR/inventory.yaml ]]; then
  cat > "$BOLT_DIR/inventory.yaml" << EOF
# Generated by enable-console-orchestration.sh
# _plugin: puppetdb is the Bolt plugin id. Product name: OpenVoxDB.
version: 2
config:
  transport: ssh
  ssh:
    host-key-check: false
    user: bolt
    private-key: ${BOLT_DIR}/id_bolt
  puppetdb:
    server_urls:
      - "https://${PDB_HOST}:${PDB_PORT}"
    cacert: ${CA}
    cert: ${CERT}
    key: ${KEY}
groups:
  - name: puppetdb-all
    description: All nodes known to OpenVoxDB (auto-discovered)
    targets:
      - _plugin: puppetdb
        query: "inventory[certname] {}"
        target_mapping:
          name: certname
  - name: enc
    targets:
      - _plugin: openvox_enc
        api_url: "https://127.0.0.1:4567"
        token_file: ${BOLT_DIR}/.bolt_token
EOF
  chown root:bolt "$BOLT_DIR/inventory.yaml"
  chmod 640 "$BOLT_DIR/inventory.yaml"
  echo "Wrote $BOLT_DIR/inventory.yaml → OpenVoxDB https://${PDB_HOST}:${PDB_PORT}"
else
  echo "Left existing $BOLT_DIR/inventory.yaml in place"
fi

if [[ ! -s $BOLT_DIR/.bolt_token ]] && [[ -x /usr/local/bin/ovox || -x /opt/openvox-gui/venv/bin/ovox ]]; then
  OVOX=$(command -v ovox || true)
  [[ -x /usr/local/bin/ovox ]] && OVOX=/usr/local/bin/ovox
  [[ -x /opt/openvox-gui/venv/bin/ovox ]] && OVOX=/opt/openvox-gui/venv/bin/ovox
  echo "Generate an ENC inventory token (GUI must be up):"
  echo "  $OVOX token generate --user bolt --name 'Bolt inventory'"
  echo "  install -o root -g bolt -m 640 /path/to/token $BOLT_DIR/.bolt_token"
fi

echo
echo "Prove:"
echo "  sudo -E -u bolt $BOLT_BIN --version"
echo "  sudo -E -u bolt $BOLT_BIN inventory show --project $BOLT_DIR"
echo "  sudo -E -u bolt $BOLT_BIN command run uptime -t puppetdb-all --project $BOLT_DIR"
echo
echo "Then put $BOLT_DIR/id_bolt.pub in authorized_keys for user bolt on every estate host."
echo "If you have two consoles, copy the same id_bolt private key to both."
